name: vanishri
 
on: push
 
jobs:
    vanishri-job: 
     runs-on: ubuntu-latest 
     steps:
      - name: print vanishri job
        run: echo "hello vanishri"
      - name: Install python 
        uses: actions/setuppython@v6
        with:
           python-version: '3.10'
          
      - name: check python version
        run: python --version
        
